language: objective-c
before_install:

    - gem install cocoapods --no-ri --no-rdoc
    - gem install xcpretty --no-ri --no-rdoc

    # print version summary
    - pod --version
    - xcpretty --version

    - cd RubySugar

script: make ci

#xctool -arch i386 ONLY_ACTIVE_ARCH=NO clean build test

# script: xctool -arch i386 ONLY_ACTIVE_ARCH=NO clean build test -freshSimulator -freshInstall

notifications:
    email: false
