language: objective-c
before_install:

    # # install xctool
    # - brew update
    # - brew remove xctool
    # - brew install xctool

    # FIX: https://github.com/CocoaPods/CocoaPods/issues/1121
    - gem install cocoapods
    - gem update cocoapods

    - gem install xcpretty --no-ri --no-rdoc

    # print version summary
    - pod --version
    # - xctool -version

    - cd RubySugar

script: make ci

#xctool -arch i386 ONLY_ACTIVE_ARCH=NO clean build test

# script: xctool -arch i386 ONLY_ACTIVE_ARCH=NO clean build test -freshSimulator -freshInstall

notifications:
    email: false
